config/routes.rb
Yks::Application.routes.draw do
  resources :system_site_maps

end

app/models/banner.rb
class Banner < ActiveRecord::Base
end

app/models/news.rb
class News < ActiveRecord::Base
end

app/models/service.rb
class Service < ActiveRecord::Base
end

app/models/system_site_map.rb
class SystemSiteMap < ActiveRecord::Base
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
end

app/models/user_exp.rb
class UserExp < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/system_site_maps_controller.rb
class SystemSiteMapsController < ApplicationController
  # GET /system_site_maps
  # GET /system_site_maps.json
  def index
    @system_site_maps = SystemSiteMap.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @system_site_maps }
    end
  end

  # GET /system_site_maps/1
  # GET /system_site_maps/1.json
  def show
    @system_site_map = SystemSiteMap.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @system_site_map }
    end
  end

  # GET /system_site_maps/new
  # GET /system_site_maps/new.json
  def new
    @system_site_map = SystemSiteMap.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @system_site_map }
    end
  end

  # GET /system_site_maps/1/edit
  def edit
    @system_site_map = SystemSiteMap.find(params[:id])
  end

  # POST /system_site_maps
  # POST /system_site_maps.json
  def create
    @system_site_map = SystemSiteMap.new(params[:system_site_map])

    respond_to do |format|
      if @system_site_map.save
        format.html { redirect_to @system_site_map, notice: 'System site map was successfully created.' }
        format.json { render json: @system_site_map, status: :created, location: @system_site_map }
      else
        format.html { render action: "new" }
        format.json { render json: @system_site_map.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /system_site_maps/1
  # PUT /system_site_maps/1.json
  def update
    @system_site_map = SystemSiteMap.find(params[:id])

    respond_to do |format|
      if @system_site_map.update_attributes(params[:system_site_map])
        format.html { redirect_to @system_site_map, notice: 'System site map was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @system_site_map.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /system_site_maps/1
  # DELETE /system_site_maps/1.json
  def destroy
    @system_site_map = SystemSiteMap.find(params[:id])
    @system_site_map.destroy

    respond_to do |format|
      format.html { redirect_to system_site_maps_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/system_site_maps_helper.rb
module SystemSiteMapsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Yks</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/system_site_maps/_form.html.erb
<%= form_for(@system_site_map) do |f| %>
  <% if @system_site_map.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@system_site_map.errors.count, "error") %> prohibited this system_site_map from being saved:</h2>

      <ul>
      <% @system_site_map.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :parent_id %><br />
    <%= f.text_field :parent_id %>
  </div>
  <div class="field">
    <%= f.label :id %><br />
    <%= f.text_field :id %>
  </div>
  <div class="field">
    <%= f.label :is_static %><br />
    <%= f.check_box :is_static %>
  </div>
  <div class="field">
    <%= f.label :controller %><br />
    <%= f.text_field :controller %>
  </div>
  <div class="field">
    <%= f.label :action %><br />
    <%= f.text_field :action %>
  </div>
  <div class="field">
    <%= f.label :parameter %><br />
    <%= f.text_field :parameter %>
  </div>
  <div class="field">
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :script %><br />
    <%= f.text_field :script %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/system_site_maps/edit.html.erb
<h1>Editing system_site_map</h1>

<%= render 'form' %>

<%= link_to 'Show', @system_site_map %> |
<%= link_to 'Back', system_site_maps_path %>

app/views/system_site_maps/index.html.erb
<h1>Listing system_site_maps</h1>

<table>
  <tr>
    <th>Parent</th>
    <th>Id</th>
    <th>Is static</th>
    <th>Controller</th>
    <th>Action</th>
    <th>Parameter</th>
    <th>Link</th>
    <th>Script</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @system_site_maps.each do |system_site_map| %>
  <tr>
    <td><%= system_site_map.parent_id %></td>
    <td><%= system_site_map.id %></td>
    <td><%= system_site_map.is_static %></td>
    <td><%= system_site_map.controller %></td>
    <td><%= system_site_map.action %></td>
    <td><%= system_site_map.parameter %></td>
    <td><%= system_site_map.link %></td>
    <td><%= system_site_map.script %></td>
    <td><%= link_to 'Show', system_site_map %></td>
    <td><%= link_to 'Edit', edit_system_site_map_path(system_site_map) %></td>
    <td><%= link_to 'Destroy', system_site_map, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New System site map', new_system_site_map_path %>

app/views/system_site_maps/new.html.erb
<h1>New system_site_map</h1>

<%= render 'form' %>

<%= link_to 'Back', system_site_maps_path %>

app/views/system_site_maps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Parent:</b>
  <%= @system_site_map.parent_id %>
</p>

<p>
  <b>Id:</b>
  <%= @system_site_map.id %>
</p>

<p>
  <b>Is static:</b>
  <%= @system_site_map.is_static %>
</p>

<p>
  <b>Controller:</b>
  <%= @system_site_map.controller %>
</p>

<p>
  <b>Action:</b>
  <%= @system_site_map.action %>
</p>

<p>
  <b>Parameter:</b>
  <%= @system_site_map.parameter %>
</p>

<p>
  <b>Link:</b>
  <%= @system_site_map.link %>
</p>

<p>
  <b>Script:</b>
  <%= @system_site_map.script %>
</p>


<%= link_to 'Edit', edit_system_site_map_path(@system_site_map) %> |
<%= link_to 'Back', system_site_maps_path %>